repos:

#- repo: https://github.com/jumanjihouse/pre-commit-hooks
#  rev: 2.1.6
#  hooks:
#    - id: shfmt
#      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
#    - id: shellcheck

# Dockerfile linter
# - repo: https://github.com/hadolint/hadolint
#   rev: v2.10.0
#   hooks:
#     - id: hadolint
#       args: [
#         '--ignore', 'DL3027', # Do not use apt
#         '--ignore', 'DL3007', # Using latest
#         '--ignore', 'DL4006', # Not related to alpine
#         '--ignore', 'SC1091', # Useless check
#         '--ignore', 'SC2015', # Useless check
#         '--ignore', 'SC3037', # Not related to alpine
#         '--ignore', 'DL3013', # Pin versions in pip
#       ]

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev:  v1.74.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      exclude: '^[^/]+$'
    - id: terraform_docs
    - id: terraform_docs_without_aggregate_type_defaults
    #- id: terraform_tflint
    #- id: terraform_tfsec
    #- id: terraform_checkov
    #- id: tfupdate
    #- id: infracost_breakdown
    #- id: terrascan

# Automatic tagging best practices - commented out since it breaks workflow of https://github.com/antonbabenko/pre-commit-terraform
# - repo: https://github.com/bridgecrewio/yor
#   rev: 0.1.143
#   hooks:
#     - id: yor
#       name: yor
#       entry: yor tag -d
#       args: ["."]
#       language: golang
#       types: [terraform]
#       pass_filenames: false

